title: WaterWall docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://radkesvat.github.io

aux_links:
  GitHub: https://github.com/radkesvat/WaterWall
