title: WaterWall docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://radkesvat.github.io

aux_links:
  GitHub: https://github.com/radkesvat/WaterWall

color_scheme: dark

enable_copy_code_button: true

callouts:
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true